apiVersion: v1
kind: ConfigMap
metadata:
  name: parks-ui-configmap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "parksApi": "http://hiking.dev/",
      "Features": {
        "parks-in-memory": true,
        "parks-api":  false
      }
    }