apiVersion: apps/v1
kind: Deployment
metadata:
  name: parks-ui
spec:
  selector:
    matchLabels:
      app: parks-ui
  template:
    metadata:
      labels:
        app: parks-ui
    spec:
      containers:
      - name: parks-ui
        image: hiking-mvc:1.0.0
        ports:
        - containerPort: 80
